First PR
incogni23/NotificationSystem pull request #1
Opened 2024-03-13 16:01 UTC by Ankitadewari

Updated service.go, consumer.go

2024-03-19 07:36 UTC, mishtuu commented on .vscode/launch.json
> +}
remove this - P2

use .gitignore

2024-03-19 07:36 UTC, mishtuu commented on .vscode/settings.json
> +}
use .gitignore - P2

2024-03-19 07:36 UTC, mishtuu commented on Timer/clock.go
> +			fmt.Print("Error getting incomplete events", err)
use log.Error, log.Info instead of fmt.Printl - P2

and this holds true across all the logs

2024-03-19 07:36 UTC, mishtuu commented on Timer/clock.go
> +			}
is this really needed? - P0


check if you can handle it directly on query level

2024-03-19 07:36 UTC, mishtuu commented on Timer/clock.go
> +			}
Once you do this, the function `GetIncompleteEvents` name should be changed to something which ties to its name

2024-03-19 07:36 UTC, mishtuu commented on Timer/clock.go
> +				event.Status = "Not Completed Yet"
should be enum - P1

2024-03-19 07:36 UTC, mishtuu commented on Timer/clock.go
> +				event.Status = "Not Completed Yet"
create a models module which will hold commonly used structs and enums - P0

2024-03-19 07:36 UTC, mishtuu commented on Timer/clock.go
> +				event.Status = "Completed"
this COMPLETED string should be the part enum

2024-03-19 07:36 UTC, mishtuu commented on Timer/clock.go
> +		return 0
this time should be greater than 0 - P0

2024-03-19 07:36 UTC, mishtuu commented on consumer/consumer.go
> +}
should be residing in 1 common module, which is models wala module - P0

2024-03-19 07:36 UTC, mishtuu commented on consumer/consumer.go
> +	//r.SetOffset()
remove - P2

2024-03-19 07:36 UTC, mishtuu commented on database/database.go
> +	dsn := "host=localhost user=pikapika password=Ankita@2307 dbname=db1 port=5432 sslmode=disable TimeZone=Asia/Kolkata"
make it configurable - P2

2024-03-19 07:36 UTC, mishtuu commented on database/database.go
> +}
shift to a common place - P0

2024-03-19 07:36 UTC, mishtuu commented on database/database.go
> +	err := db.Where("status = ?", "Not Completed Yet").Find(&events).Error
Not Completed Yet - should be served from enum

2024-03-19 07:36 UTC, mishtuu commented on producer/producer.go
> +
move it to common place

2024-03-19 07:36 UTC, mishtuu commented on services/notification_services/service.go
> +}
remove this - P0

2024-03-19 07:40 UTC, Ankitadewari commented on .vscode/launch.json
> +}
huh bleh.

2024-03-19 21:51 UTC, mishtuu commented
max retry attempts should be limited to 5, and this number needs to be configurable

2024-03-19 21:52 UTC, mishtuu commented
to make things configurable you can checkout this repo
https://github.com/ilyakaznacheev/cleanenv

2024-03-19 21:52 UTC, mishtuu requested changes

2024-03-19 21:52 UTC, mishtuu commented on services/notification_services/service.go
> +func Deliver(event consumer.Event, notificationType string) error {
apart from error, send one more parameter `isRetryble` (bool)

2024-03-19 21:52 UTC, mishtuu commented on services/notification_services/service.go
> +		return errors.New("notification type required")
here we will set isRetryable as false

2024-03-20 22:00 UTC, mishtuu commented on models/models.go
> +const Topicname string = "quickstart-events" // for consumer
use env

2024-03-20 22:00 UTC, mishtuu commented on services/notification_services/webhook/service.go
> +		}
think and change

2024-03-21 00:44 UTC, Ankitadewari commented on services/notification_services/webhook/service.go
> +		}
i am not so sure on this one

2024-04-08 08:14 UTC, merged