added login and signup
incogni23/NotificationSystem pull request #15
Opened 2024-04-24 14:57 UTC by incogni23

2024-04-24 18:27 UTC, shubham-aurva requested changes

2024-04-24 18:27 UTC, shubham-aurva commented on auth/dao.go
> +//else : err
remove them

2024-04-24 18:27 UTC, shubham-aurva commented on auth/dao.go
> +func (db *dao) InsertUser(u User) error {
variable name shouldn't be just `u`

2024-04-24 18:27 UTC, shubham-aurva commented on auth/dao.go
> +	return &user, nil
try to put some extra lines before a block for better readability

2024-04-24 18:27 UTC, shubham-aurva commented on auth/service.go
> +}
put it into a different file `models.go`

2024-04-24 18:27 UTC, shubham-aurva commented on auth/service.go
> +	LoginWithToken(tokenString string) (string, error)
why do we need this?

2024-04-24 18:27 UTC, shubham-aurva commented on auth/service.go
> +func (dbv *DBVar) SignUp(u User) error {
variable name should be proper

2024-04-24 18:27 UTC, shubham-aurva commented on auth/service_test.go
> +	})
Wrong test cases. Should test login functionality, not the signup

2024-04-24 18:27 UTC, shubham-aurva commented on auth/service.go
> +//Login
remove

2024-06-08 11:38 UTC, mishtuu approved these changes

2024-06-08 11:39 UTC, merged