Ft/basic server // payment
incogni23/NotificationSystem pull request #23
Opened 2024-05-19 21:23 UTC by incogni23

worked on issue 1 and 2

2024-05-19 21:34 UTC, shubham-aurva approved these changes

2024-05-25 17:01 UTC, incogni23 commented
worked on config APIs

2024-05-25 19:41 UTC, shubham-aurva requested changes

2024-05-25 19:41 UTC, shubham-aurva commented on auth/service.go
> +func (dbv *DBVar) SignUp(incomingUser *User) (*User, error) {
name it just `service`

2024-05-25 19:41 UTC, shubham-aurva commented on auth/service.go
>  	if err != nil {
put this condition on top

2024-05-25 19:41 UTC, shubham-aurva commented on services/monolith/configurations/config.go
> +func (dbc *DBConfig) PaymentMethod(c *gin.Context) {
GetPaymentMethod should be the name

2024-05-25 19:41 UTC, shubham-aurva commented on services/monolith/configurations/config.go
> +package configurations
file name should be endpoint.go

2024-05-25 19:41 UTC, shubham-aurva commented on services/monolith/main.go
> +		&payments.PaymentConfiguration{},
this shouldn't be the part of global db

2024-05-25 19:41 UTC, shubham-aurva commented on services/monolith/dependencies/seed.go
> +func SeedPayment(db *gorm.DB) {
name it either Seed or something on the lines of `SeedPaymentProperties`

2024-05-25 19:41 UTC, shubham-aurva commented on services/monolith/dependencies/seed.go
> +func Initconfig(db *gorm.DB, config payments.PaymentConfiguration) error {
remove this

2024-05-25 19:41 UTC, shubham-aurva commented on services/monolith/main.go
> +	r.GET("/payment_method/:method_id", configService.PaymentMethod)
this should be called via protectedGroup

2024-05-25 19:41 UTC, shubham-aurva commented on services/monolith/configurations/config.go
> +	err = dbc.DB.Create(&paymentConfig).Error
So there will be few checks before inserting this data to database
The first check is to validate that strings are not empty (PAYMENT METHOD AND PAYMENT GATEWAT != "")

The second check is to validate that PAYMENT GATEWAY is actually exisiting in our database (ensuring we have a support it) and we should be able to query the id as well

The third check is to validate that PAYMENT METHOD is actually exisiting in our database (ensuring we have a support it)

2024-05-25 19:41 UTC, shubham-aurva commented on services/monolith/configurations/config.go
> +	err = dbc.DB.Create(&paymentConfig).Error
if any of them fails, we should result an error

2024-06-08 11:37 UTC, mishtuu approved these changes

2024-06-08 11:38 UTC, merged